### ISSUE TITLE
Make a new patch release with the updated dependencies

### ISSUE THREAD

**Issue by jounathaen** [stm32-rs/stm32f407g-disc#23]
@therealprof I think a new 0.4.1 with the updated dependencies would be nice. This could then also fix #22 

I created a branch with the version Bump https://github.com/stm32-rs/stm32f407g-disc/tree/0.4.1 but I don't have the permissions to publish it.

**Comment by therealprof** [comment]
If you merge the branch (or turn it into a PR before and then merge it) I can publish it.
